import 'dart:math' as math;
import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/baby.dart';
import '../models/consistency.dart';
import '../models/poop_color.dart';
import '../models/poop_entry.dart';
import '../models/poop_size.dart';

enum DiaryExportPeriod {
  week(7, 'Last week'),
  twoWeeks(14, 'Last 2 weeks'),
  month(30, 'Last month');

  const DiaryExportPeriod(this.days, this.label);

  final int days;
  final String label;
}

class DiaryPdfExportService {
  const DiaryPdfExportService();

  List<PoopEntry> entriesForPeriod({
    required List<PoopEntry> entries,
    required DiaryExportPeriod period,
    required DateTime now,
  }) {
    final start = DateTime(now.year, now.month, now.day)
        .subtract(Duration(days: period.days - 1));
    return entries
        .where((entry) =>
            !entry.timestamp.isBefore(start) && !entry.timestamp.isAfter(now))
        .toList()
      ..sort((a, b) => a.timestamp.compareTo(b.timestamp));
  }

  Future<Uint8List> build({
    required Baby baby,
    required List<PoopEntry> entries,
    required DiaryExportPeriod period,
    DateTime? now,
  }) async {
    final exportTime = now ?? DateTime.now();
    final periodEntries = entriesForPeriod(
      entries: entries,
      period: period,
      now: exportTime,
    );
    final start = DateTime(exportTime.year, exportTime.month, exportTime.day)
        .subtract(Duration(days: period.days - 1));
    final document = pw.Document();

    document.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          margin: const pw.EdgeInsets.all(36),
          theme: pw.ThemeData.withFont(
            base: pw.Font.helvetica(),
            bold: pw.Font.helveticaBold(),
          ),
        ),
        build: (context) => [
          pw.Text(
            '${baby.name} - Diary summary',
            style: pw.TextStyle(
              fontSize: 24,
              fontWeight: pw.FontWeight.bold,
              color: PdfColor.fromInt(0xFF2E7D32),
            ),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            '${period.label}: ${DateFormat('MMM d, y').format(start)} to ${DateFormat('MMM d, y').format(exportTime)}',
            style: const pw.TextStyle(color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 24),
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: PdfColor.fromInt(0xFFE8F5E9),
              borderRadius: pw.BorderRadius.circular(8),
            ),
            child: pw.Row(
              children: [
                pw.Text(
                  '${periodEntries.length}',
                  style: pw.TextStyle(
                    fontSize: 32,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColor.fromInt(0xFF2E7D32),
                  ),
                ),
                pw.SizedBox(width: 12),
                pw.Text(
                  periodEntries.length == 1 ? 'poop logged' : 'poops logged',
                  style: const pw.TextStyle(fontSize: 15),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Daily activity',
            style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          _dailyChart(start: start, period: period, entries: periodEntries),
          pw.SizedBox(height: 24),
          _breakdown(
            title: 'Consistency',
            values: Consistency.values,
            entries: periodEntries,
            labelFor: (value) => value.label,
            valueFor: (entry) => entry.consistency,
          ),
          pw.SizedBox(height: 18),
          _breakdown(
            title: 'Size',
            values: PoopSize.values,
            entries: periodEntries,
            labelFor: (value) => value.label,
            valueFor: (entry) => entry.size,
          ),
          pw.SizedBox(height: 18),
          _breakdown(
            title: 'Color',
            values: PoopColor.values,
            entries: periodEntries,
            labelFor: (value) => value.label,
            valueFor: (entry) => entry.color,
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by Potty Tracker on ${DateFormat('MMM d, y').format(exportTime)}.',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );
    return document.save();
  }

  pw.Widget _dailyChart({
    required DateTime start,
    required DiaryExportPeriod period,
    required List<PoopEntry> entries,
  }) {
    final dailyCounts = List<int>.generate(period.days, (index) {
      final day = start.add(Duration(days: index));
      return entries
          .where((entry) =>
              entry.timestamp.year == day.year &&
              entry.timestamp.month == day.month &&
              entry.timestamp.day == day.day)
          .length;
    });
    final highestCount = math.max(1, dailyCounts.fold(0, math.max));
    final labelInterval = period.days <= 7
        ? 1
        : period.days <= 14
            ? 2
            : 5;

    return pw.Container(
      height: 150,
      padding: const pw.EdgeInsets.fromLTRB(8, 8, 8, 0),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text('Daily poops (up to $highestCount)',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
          pw.SizedBox(height: 4),
          pw.Expanded(
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.stretch,
              children: List.generate(period.days, (index) {
                final count = dailyCounts[index];
                final day = start.add(Duration(days: index));
                final showLabel =
                    index % labelInterval == 0 || index == period.days - 1;
                final barHeight =
                    count == 0 ? 0.0 : math.max(3, 82 * count / highestCount);
                return pw.Expanded(
                  child: pw.Column(
                    children: [
                      pw.Expanded(
                        child: pw.Align(
                          alignment: pw.Alignment.bottomCenter,
                          child: pw.Container(
                            width: period.days > 14 ? 6 : 12,
                            height: barHeight,
                            decoration: pw.BoxDecoration(
                              color: PdfColor.fromInt(0xFF4CAF50),
                              borderRadius: pw.BorderRadius.circular(2),
                            ),
                          ),
                        ),
                      ),
                      pw.SizedBox(height: 3),
                      pw.Text(
                        showLabel ? DateFormat('M/d').format(day) : '',
                        style: const pw.TextStyle(fontSize: 5),
                      ),
                    ],
                  ),
                );
              }),
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _breakdown<T>({
    required String title,
    required List<T> values,
    required List<PoopEntry> entries,
    required String Function(T value) labelFor,
    required T? Function(PoopEntry entry) valueFor,
  }) {
    final knownEntries =
        entries.where((entry) => valueFor(entry) != null).toList();
    if (knownEntries.isEmpty) {
      return _section(title, const [pw.Text('N/A - not recorded')]);
    }
    final unknownCount = entries.length - knownEntries.length;
    final items = values
        .map((value) =>
            '${labelFor(value)}: ${knownEntries.where((entry) => valueFor(entry) == value).length}')
        .toList();
    if (unknownCount > 0) items.add('Not recorded: $unknownCount');
    return _section(
      title,
      [
        pw.Wrap(
          spacing: 8,
          runSpacing: 8,
          children: items
              .map(
                (item) => pw.Container(
                  padding:
                      const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 6),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    borderRadius: pw.BorderRadius.circular(4),
                  ),
                  child: pw.Text(item, style: const pw.TextStyle(fontSize: 10)),
                ),
              )
              .toList(),
        ),
      ],
    );
  }

  pw.Widget _section(String title, List<pw.Widget> children) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title,
              style:
                  pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          ...children,
        ],
      );
}
